name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodules
      uses: actions/checkout@v4
    - name: Formatting
      uses: github/super-linter@v7
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  